#include <stdio.h>
#include <stdlib.h>
#include "util.h"

/**
 * @brief to generate a sequence using Collatz conjecture and
 * recursively algorithm
 * 
 * @param xs > first element of the sequence
 * @param currentlen > for recursive
 * @param seqlen > length of the sequence
 * @param seq > sequence array to return
 */
void	generate_sequence(int xs, int currentlen, int seqlen, int *seq)
{
	if (currentlen != seqlen)
	{
		seq[currentlen++] = xs;

		/* bitwise and operator for number is odd or not */
		if (xs & 1) /* odd */
			xs = 3*xs + 1;
		else /* even */
			xs >>= 1; /* right shifting to divide by two */
		generate_sequence(xs, currentlen, seqlen, seq);
	}
}

/**
 * @brief Return 1 if there is a loop, 0 otherwise.
 * 
 * @param arr 
 * @param n 
 * @param looplen 
 * @param ls 
 * @param le 
 * @return int
 */
int	has_loop(int *arr, int n, int looplen, int *ls, int *le)
{
	int	flag = 1, i, isPrimaryLoop = 1;

	for (i = 0; i < looplen; i++)
		if (arr[n -1 - i] != arr[n -1 - looplen - i])
			flag = 0;

	if (flag)
	{
		(*ls) = n - 2 * looplen;
		(*le) = n - 1 - looplen;
	}

	if ((*ls) > (*le) - (*ls))
		for (i = (*le); i >= (*ls); i--)
		{
			if (arr[i] != arr[i - looplen])
				isPrimaryLoop = 0;
		}
	else
		isPrimaryLoop = 0;

	if (isPrimaryLoop)
	{
		(*ls) -= 3;
		(*le) -= 3;
	}

	return (flag);
}

/**
 * @brief to check if the sequence ends up in a loop
 * with a recursively algorithm.
 * 
 * @param f > function parameter
 * @param xs 
 * @param seqlen 
 * @param loop 
 * @param looplen 
 */
void	check_loop_iterative(void (*f)(int, int, int, int*), int xs, int seqlen, int *loop, int *looplen)
{
	int	*arr = (int *)calloc(seqlen, sizeof(int));
	int	ls, le;
	f(xs, 0, seqlen, arr);

	printf("\nChecking if there is a loop of length %d...", (*looplen));

	if (has_loop(arr, seqlen, *looplen, &ls, &le))
	{
		printf("\n\nLoop detected with a length of %d.", (*looplen));
		printf("\nThe indexes of the loop's first occurance: %d (first digit), %d (last digit)", ls, le);
		for (int i = ls, j = 0; j < (*looplen); i++, j++)
			loop[j] = arr[i];
		free(arr);
		return;
	}

	if ((*looplen) > 2)
	{
		(*looplen)--;
		check_loop_iterative(f, xs, seqlen, loop, looplen);
	}
	free(arr);
}

/**
 * @brief This recursive function calculates the histogram of the first digits
 * of the sequence generated by a given function.
 * 
 * @param f 
 * @param xs 
 * @param seqlen 
 * @param h 
 * @param digit 
 */
void	hist_of_firstdigits(void (*f)(int, int, int, int*), int xs, int seqlen, int *h, int digit)
{
	int	*arr = (int *)calloc(seqlen, sizeof(int));
	f(xs, 0, seqlen, arr);

	/* recursive digit func */
	convert_ints_to_digits(arr, seqlen);

	for (int i = 0; i < seqlen; i++)
		if (arr[i] == digit)
			h[digit - 1]++;
	
	if (digit != 9)
		hist_of_firstdigits(f, xs, seqlen, h, digit + 1);
	
	free(arr);
}

/**
 * @brief to convert the integers of the given array to the first digits of this integers
 * using a recursively algorithm
 * 
 * @param arr 
 * @param arrLen 
 */
void	convert_ints_to_digits(int *arr, int arrLen)
{
	for (int i = 0; i < arrLen; i++)
	{
		if (arr[i] >= 10)
		{
			arr[i] /= 10;
			convert_ints_to_digits(arr, arrLen);
		}
	}
}

/**
 * @brief to print one dimensional array with curly braces
 * 
 * @param arr 
 * @param arrlen 
 */
void	print_arr(int *arr, int arrlen)
{
	printf("{");
	for (int i = 0; i < arrlen; i++)
		printf("%d, ", arr[i]);
	printf("\b\b}\n");
}